web:
  build: .
  ports:
    - "8080:4567"
  volumes:
    - .:/usr/src/app
  links:
    - redis
    - elasticsearch
  environment:
    - RACK_ENV=development
redis:
  image: redis
elasticsearch:
  image: elasticsearch
